# Generated by Django 6.0.3 on 2026-07-16 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], db_index=True, max_length=20)),
                ('format', models.CharField(choices=[('swiss', 'Swiss System'), ('round_robin', 'Round Robin'), ('elimination', 'Knockout'), ('double_elimination', 'Double Elimination')], default='swiss', max_length=20)),
                ('rounds', models.PositiveIntegerField(default=7)),
                ('time_control', models.CharField(help_text="e.g., '90+30', '15+10'", max_length=20)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_players', models.PositiveIntegerField(default=32)),
                ('current_players', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(db_index=True, max_length=255)),
                ('rating', models.PositiveIntegerField(db_index=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], max_length=20)),
                ('points', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('buchholz', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sonneborn_berger', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ttsaadmin.tournament')),
            ],
            options={
                'ordering': ['-points', '-buchholz', '-sonneborn_berger', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(db_index=True)),
                ('board_number', models.PositiveIntegerField()),
                ('pairing_method', models.CharField(default='swiss', max_length=50)),
                ('color_preference', models.CharField(default='balanced', max_length=10)),
                ('white_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('black_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_difference', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mutual_games', models.PositiveIntegerField(default=0, help_text='Number of times these players have faced each other')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='ttsaadmin.tournament')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_pairings', to='ttsaadmin.tournamentplayer')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_pairings', to='ttsaadmin.tournamentplayer')),
            ],
            options={
                'ordering': ['round_number', 'board_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(db_index=True)),
                ('board_number', models.PositiveIntegerField(db_index=True)),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('½-½', 'Draw'), ('*', 'Not Started/In Progress')], db_index=True, default='*', max_length=5)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('adjourned', 'Adjourned'), ('forfeit', 'Forfeit')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pgn', models.TextField(blank=True, help_text='PGN notation of the game')),
                ('moves_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='ttsaadmin.tournament')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='ttsaadmin.tournamentplayer')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='ttsaadmin.tournamentplayer')),
            ],
            options={
                'ordering': ['round_number', 'board_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('½-½', 'Draw'), ('*', 'Not Started/In Progress')], max_length=5)),
                ('result_method', models.CharField(default='normal', max_length=50)),
                ('white_time_remaining', models.CharField(blank=True, max_length=20)),
                ('black_time_remaining', models.CharField(blank=True, max_length=20)),
                ('moves', models.TextField(blank=True, help_text='Full move list in algebraic notation')),
                ('opening', models.CharField(blank=True, max_length=100)),
                ('termination', models.CharField(blank=True, max_length=100)),
                ('points_awarded', models.BooleanField(default=False)),
                ('standings_updated', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_result', to='ttsaadmin.tournamentgame')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pairing', 'Pairing'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pairings_generated_at', models.DateTimeField(blank=True, null=True)),
                ('time_control', models.CharField(help_text='Time control for this round', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bye_players', models.ManyToManyField(blank=True, related_name='bye_rounds', to='ttsaadmin.tournamentplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rounds', to='ttsaadmin.tournament')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(db_index=True)),
                ('points', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('buchholz', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6)),
                ('sonneborn_berger', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6)),
                ('cumulative_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('progressive_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('white_games', models.PositiveIntegerField(default=0)),
                ('black_games', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='ttsaadmin.tournamentplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='ttsaadmin.tournament')),
            ],
            options={
                'ordering': ['-points', '-buchholz', '-sonneborn_berger', 'player__player_name'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('channel_url', models.URLField(max_length=255, unique=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_description', models.TextField(blank=True)),
                ('channel_thumbnail_url', models.URLField(blank=True, max_length=255)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_id'], name='ttsaadmin_y_channel_5b3c4c_idx'), models.Index(fields=['channel_name'], name='ttsaadmin_y_channel_cfb70a_idx'), models.Index(fields=['is_active'], name='ttsaadmin_y_is_acti_a2e93b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('video_added', 'Video Added')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('video_title', models.CharField(blank=True, max_length=255)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('videos_added', models.IntegerField(default=0)),
                ('videos_skipped', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ttsaadmin_s_user_id_30db4f_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='ttsaadmin_s_user_id_898f82_idx'), models.Index(fields=['notification_type', '-created_at'], name='ttsaadmin_s_notific_7668d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['name'], name='ttsaadmin_t_name_aaeac9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['category', 'status'], name='ttsaadmin_t_categor_e18e73_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date', 'status'], name='ttsaadmin_t_start_d_0bdf80_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_by', '-created_at'], name='ttsaadmin_t_created_0ce45f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_active', 'status', '-start_date'], name='ttsaadmin_t_is_acti_f1f0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', '-points'], name='ttsaadmin_t_tournam_e326fd_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', 'status'], name='ttsaadmin_t_tournam_b4a1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', 'rank'], name='ttsaadmin_t_tournam_b976f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['rating'], name='ttsaadmin_t_rating_c80b30_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['player_name'], name='ttsaadmin_t_player__3b201e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together={('tournament', 'player_name')},
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['tournament', 'round_number', 'board_number'], name='ttsaadmin_t_tournam_4b863b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['white_player', 'tournament'], name='ttsaadmin_t_white_p_d9364b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentpairing',
            index=models.Index(fields=['black_player', 'tournament'], name='ttsaadmin_t_black_p_6e762a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentpairing',
            unique_together={('tournament', 'round_number', 'board_number')},
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'round_number', 'board_number'], name='ttsaadmin_t_tournam_04733a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['white_player', 'tournament'], name='ttsaadmin_t_white_p_3fc70a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['black_player', 'tournament'], name='ttsaadmin_t_black_p_0158a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'status'], name='ttsaadmin_t_tournam_ee88ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'result'], name='ttsaadmin_t_tournam_03852a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['scheduled_time'], name='ttsaadmin_t_schedul_a08a49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgame',
            unique_together={('tournament', 'round_number', 'board_number')},
        ),
        migrations.AddIndex(
            model_name='tournamentresult',
            index=models.Index(fields=['game', 'result'], name='ttsaadmin_t_game_id_55d80c_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentresult',
            index=models.Index(fields=['entered_at'], name='ttsaadmin_t_entered_bed700_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['tournament', 'round_number'], name='ttsaadmin_t_tournam_b7829d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['status'], name='ttsaadmin_t_status_5a09ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='tournamentstanding',
            index=models.Index(fields=['tournament', 'round_number', '-points'], name='ttsaadmin_t_tournam_b7704d_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstanding',
            index=models.Index(fields=['tournament', 'player', 'round_number'], name='ttsaadmin_t_tournam_6b7638_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstanding',
            index=models.Index(fields=['rank'], name='ttsaadmin_t_rank_15f941_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentstanding',
            unique_together={('tournament', 'player', 'round_number')},
        ),
    ]
