# Generated by Django 4.2.7 on 2026-07-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('channel_url', models.URLField(max_length=500, unique=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_description', models.TextField(blank=True)),
                ('channel_thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_id'], name='ttsaadmin_y_channel_5b3c4c_idx'), models.Index(fields=['channel_name'], name='ttsaadmin_y_channel_cfb70a_idx'), models.Index(fields=['is_active'], name='ttsaadmin_y_is_acti_a2e93b_idx')],
            },
        ),
    ]
