# Generated by Django 4.2.7 on 2026-07-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='subscriber_count',
        ),
    ]
