# Generated by Django 4.2.7 on 2026-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0002_remove_youtubechannel_subscriber_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_thumbnail_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
