# Generated by Django 4.2.7 on 2026-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0002_alter_syncnotification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='TTSA Chess Academy', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academy Settings',
                'verbose_name_plural': 'Academy Settings',
            },
        ),
    ]
