# Generated by Django 6.0.3 on 2026-07-13 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0003_alter_youtubechannel_channel_thumbnail_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('video_added', 'Video Added')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('video_title', models.CharField(blank=True, max_length=255)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('videos_added', models.IntegerField(default=0)),
                ('videos_skipped', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ttsaadmin_s_user_id_30db4f_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='ttsaadmin_s_user_id_898f82_idx'), models.Index(fields=['notification_type', '-created_at'], name='ttsaadmin_s_notific_7668d8_idx')],
            },
        ),
    ]
