# Generated by Django 6.0.3 on 2026-07-14 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0004_syncnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], db_index=True, max_length=20)),
                ('format', models.CharField(choices=[('swiss', 'Swiss System'), ('round_robin', 'Round Robin'), ('elimination', 'Knockout'), ('double_elimination', 'Double Elimination')], default='swiss', max_length=20)),
                ('rounds', models.PositiveIntegerField(default=7)),
                ('time_control', models.CharField(help_text="e.g., '90+30', '15+10'", max_length=20)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_players', models.PositiveIntegerField(default=32)),
                ('current_players', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration', 'Registration Open'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(db_index=True, max_length=255)),
                ('rating', models.PositiveIntegerField(db_index=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], max_length=20)),
                ('points', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('buchholz', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sonneborn_berger', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ttsaadmin.tournament')),
            ],
            options={
                'ordering': ['-points', '-buchholz', '-sonneborn_berger', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(db_index=True)),
                ('board_number', models.PositiveIntegerField(db_index=True)),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('½-½', 'Draw'), ('*', 'Not Started/In Progress')], db_index=True, default='*', max_length=5)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('adjourned', 'Adjourned'), ('forfeit', 'Forfeit')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pgn', models.TextField(blank=True, help_text='PGN notation of the game')),
                ('moves_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='ttsaadmin.tournament')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='ttsaadmin.tournamentplayer')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='ttsaadmin.tournamentplayer')),
            ],
            options={
                'ordering': ['round_number', 'board_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['name'], name='ttsaadmin_t_name_aaeac9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['category', 'status'], name='ttsaadmin_t_categor_e18e73_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date', 'status'], name='ttsaadmin_t_start_d_0bdf80_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_by', '-created_at'], name='ttsaadmin_t_created_0ce45f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_active', 'status', '-start_date'], name='ttsaadmin_t_is_acti_f1f0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', '-points'], name='ttsaadmin_t_tournam_e326fd_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', 'status'], name='ttsaadmin_t_tournam_b4a1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['tournament', 'rank'], name='ttsaadmin_t_tournam_b976f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['rating'], name='ttsaadmin_t_rating_c80b30_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['player_name'], name='ttsaadmin_t_player__3b201e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together={('tournament', 'player_name')},
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'round_number', 'board_number'], name='ttsaadmin_t_tournam_04733a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['white_player', 'tournament'], name='ttsaadmin_t_white_p_3fc70a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['black_player', 'tournament'], name='ttsaadmin_t_black_p_0158a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'status'], name='ttsaadmin_t_tournam_ee88ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['tournament', 'result'], name='ttsaadmin_t_tournam_03852a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentgame',
            index=models.Index(fields=['scheduled_time'], name='ttsaadmin_t_schedul_a08a49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgame',
            unique_together={('tournament', 'round_number', 'board_number')},
        ),
    ]
