# Generated by Django 6.0.3 on 2026-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0004_tournament_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration', 'Open for Registration'), ('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
    ]
