# Generated by Django 6.0.3 on 2026-09-01 16:47

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Tournament = apps.get_model('ttsaadmin', 'Tournament')
    for tournament in Tournament.objects.all():
        if not tournament.slug:
            base_slug = slugify(tournament.name)
            slug = base_slug
            counter = 1
            # Ensure slug is unique
            while Tournament.objects.filter(slug=slug).exclude(id=tournament.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            tournament.slug = slug
            tournament.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0005_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
    ]
