# Generated by Django 6.0.3 on 2026-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0006_tournament_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='certificate_available',
            field=models.BooleanField(default=True, help_text='Whether certificates are available for participants'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='first_place_prize',
            field=models.CharField(blank=True, help_text='Prize for first place', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_place_prize',
            field=models.CharField(blank=True, help_text='Prize for second place', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place_prize',
            field=models.CharField(blank=True, help_text='Prize for third place', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
