# Generated by Django 4.2.7 on 2026-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0007_tournament_certificate_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='rating_deviation',
            field=models.FloatField(default=350.0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='volatility',
            field=models.FloatField(default=0.06),
        ),
    ]
