# Generated by Django 4.2.7 on 2026-09-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttsaadmin', '0008_tournamentplayer_rating_deviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], max_length=20)),
                ('points', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('buchholz', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sonneborn_berger', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-points', '-buchholz', '-sonneborn_berger', 'team_name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='team_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='ttsaadmin.tournamentplayer'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ttsaadmin.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='ttsaadmin.tournamentteam'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together={('tournament', 'player_name', 'team')},
        ),
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['team'], name='ttsaadmin_t_team_id_8b4430_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', '-points'], name='ttsaadmin_t_tournam_762fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', 'status'], name='ttsaadmin_t_tournam_a7faeb_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', 'rank'], name='ttsaadmin_t_tournam_daaa52_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['team_name'], name='ttsaadmin_t_team_na_9cd15e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team_name')},
        ),
    ]
