# Generated by Django 6.0.3 on 2026-07-16 11:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('games', 'Games'), ('lessons', 'Lessons'), ('puzzles', 'Puzzles'), ('streak', 'Learning Streak'), ('special', 'Special')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('player', 'Player'), ('player_plus', 'Player Plus'), ('ttsa_admin', 'TTSA Admin')], db_index=True, default='player', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'ttsa_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('basics', 'Chess Basics'), ('openings', 'Openings'), ('tactics', 'Tactics'), ('endgames', 'Endgames'), ('strategy', 'Strategy')], db_index=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_interactive', models.BooleanField(default=True)),
                ('points_reward', models.IntegerField(default=10)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'order'], name='ttsa_app_le_categor_153858_idx'), models.Index(fields=['difficulty', 'order'], name='ttsa_app_le_difficu_024c33_idx')],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('game_type', models.CharField(choices=[('standard', 'Standard Chess'), ('blitz', 'Blitz (5+0)'), ('rapid', 'Rapid (10+0)'), ('classical', 'Classical (30+0)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('playing', 'Game in progress'), ('completed', 'Game completed'), ('abandoned', 'Game abandoned')], db_index=True, default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('white', 'White wins'), ('black', 'Black wins'), ('draw', 'Draw'), ('resignation', 'Resignation'), ('timeout', 'Timeout'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('current_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('pgn', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('rated', models.BooleanField(default=False)),
                ('color_preference', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('white_time', models.IntegerField(default=600)),
                ('black_time', models.IntegerField(default=600)),
                ('last_move_timestamp', models.DateTimeField(blank=True, null=True)),
                ('active_clock', models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=10)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_from', models.CharField(max_length=2)),
                ('move_to', models.CharField(max_length=2)),
                ('piece', models.CharField(max_length=1)),
                ('captured_piece', models.CharField(blank=True, max_length=1, null=True)),
                ('promotion', models.CharField(blank=True, max_length=1, null=True)),
                ('castling', models.CharField(blank=True, max_length=10, null=True)),
                ('en_passant', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('fen_after', models.TextField()),
                ('move_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='ttsa_app.multiplayergame')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('tournaments_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizer Profile',
                'verbose_name_plural': 'Organizer Profiles',
                'db_table': 'ttsa_organizer_profile',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('rating', models.IntegerField(default=800)),
                ('coins', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('learning_streak', models.IntegerField(default=0)),
                ('last_played', models.DateField(default=django.utils.timezone.now)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.lesson')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='ttsa_app.playerprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_rank', models.IntegerField(default=0)),
                ('monthly_rank', models.IntegerField(default=0)),
                ('all_time_rank', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('monthly_points', models.IntegerField(default=0)),
                ('all_time_points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='ttsa_app.playerprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], db_index=True, max_length=5)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], db_index=True, max_length=20)),
                ('pgn', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], db_index=True, default='ongoing', max_length=20)),
                ('moves_count', models.IntegerField(default=0)),
                ('time_elapsed', models.DurationField(default=datetime.timedelta)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('tactics', 'Tactics'), ('checkmate', 'Checkmate'), ('endgame', 'Endgame')], db_index=True, max_length=50)),
                ('rating', models.IntegerField(default=1200)),
                ('daily', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['daily', 'difficulty'], name='ttsa_app_pu_daily_ef0bb0_idx'), models.Index(fields=['category', 'difficulty'], name='ttsa_app_pu_categor_357fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('channel_name', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(choices=[('openings', 'Openings'), ('middlegame', 'Middlegame'), ('endgames', 'Endgames'), ('tactics', 'Tactics'), ('strategy', 'Strategy')], db_index=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'difficulty', 'order'], name='ttsa_app_vi_categor_a83f1a_idx'), models.Index(fields=['title'], name='ttsa_app_vi_title_336f86_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='ttsa_app_ac_publish_875d4f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['status', '-created_at'], name='ttsa_app_mu_status_89c6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['white_player', 'status'], name='ttsa_app_mu_white_p_d329ce_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['black_player', 'status'], name='ttsa_app_mu_black_p_5190c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['game', 'move_number'], name='ttsa_app_ga_game_id_204d71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerlesson',
            unique_together={('player', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='playerachievement',
            unique_together={('player', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', '-created_at'], name='ttsa_app_me_receive_a2dfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='ttsa_app_me_sender__ce4d70_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'read', '-created_at'], name='ttsa_app_me_receive_e91ff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['player', '-created_at'], name='ttsa_app_ch_player__57b65d_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['result', 'created_at'], name='ttsa_app_ch_result_0d47b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerpuzzle',
            unique_together={('player', 'puzzle')},
        ),
    ]
