# Generated by Django 4.2.7 on 2026-07-17 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_info', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, max_length=1000)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_player_plus_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_plus_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ttsa_player_plus_application',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ttsa_player_user_id_fbee9b_idx'), models.Index(fields=['status', '-submitted_at'], name='ttsa_player_status_ff8d82_idx')],
            },
        ),
    ]
