# Generated by Django 5.1.1 on 2026-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('channel_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('openings', 'Openings'), ('middlegame', 'Middlegame'), ('endgames', 'Endgames'), ('tactics', 'Tactics'), ('strategy', 'Strategy')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
