# Generated by Django 4.2.7 on 2026-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0003_videolesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academynews',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='academynews',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('master', 'Master')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='player_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='result',
            field=models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], db_index=True, default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('basics', 'Chess Basics'), ('openings', 'Openings'), ('tactics', 'Tactics'), ('endgames', 'Endgames'), ('strategy', 'Strategy')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='multiplayergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='multiplayergame',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for opponent'), ('playing', 'Game in progress'), ('completed', 'Game completed'), ('abandoned', 'Game abandoned')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='category',
            field=models.CharField(choices=[('tactics', 'Tactics'), ('checkmate', 'Checkmate'), ('endgame', 'Endgame')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='daily',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='category',
            field=models.CharField(choices=[('openings', 'Openings'), ('middlegame', 'Middlegame'), ('endgames', 'Endgames'), ('tactics', 'Tactics'), ('strategy', 'Strategy')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='academynews',
            index=models.Index(fields=['-published_at'], name='ttsa_app_ac_publish_875d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['player', '-created_at'], name='ttsa_app_ch_player__57b65d_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['result', 'created_at'], name='ttsa_app_ch_result_0d47b2_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['game', 'move_number'], name='ttsa_app_ga_game_id_204d71_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['category', 'order'], name='ttsa_app_le_categor_153858_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['difficulty', 'order'], name='ttsa_app_le_difficu_024c33_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', '-created_at'], name='ttsa_app_me_receive_a2dfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='ttsa_app_me_sender__ce4d70_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'read', '-created_at'], name='ttsa_app_me_receive_e91ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['status', '-created_at'], name='ttsa_app_mu_status_89c6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['white_player', 'status'], name='ttsa_app_mu_white_p_d329ce_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayergame',
            index=models.Index(fields=['black_player', 'status'], name='ttsa_app_mu_black_p_5190c8_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['daily', 'difficulty'], name='ttsa_app_pu_daily_ef0bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['category', 'difficulty'], name='ttsa_app_pu_categor_357fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='videolesson',
            index=models.Index(fields=['category', 'difficulty', 'order'], name='ttsa_app_vi_categor_a83f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='videolesson',
            index=models.Index(fields=['title'], name='ttsa_app_vi_title_336f86_idx'),
        ),
    ]
