# Generated by Django 4.2.7 on 2026-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0004_alter_academynews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='active_clock',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='black_time',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='last_move_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplayergame',
            name='white_time',
            field=models.IntegerField(default=600),
        ),
    ]
