# Generated by Django 6.0.3 on 2026-07-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0004_multiplayergame_color_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
    ]
