# Generated by Django 4.2.7 on 2026-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0005_multiplayergame_active_clock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='ttsa_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
