# Generated by Django 4.2.7 on 2026-07-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0006_playerprofile_ttsa_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
