# Generated by Django 6.0.3 on 2026-07-19 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0006_alter_academynews_author_alter_gamemove_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='last_played',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='views',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['weekly_rank'], name='ttsa_app_le_weekly__4ebbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['monthly_rank'], name='ttsa_app_le_monthly_130116_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['all_time_rank'], name='ttsa_app_le_all_tim_aac345_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['player', '-all_time_points'], name='ttsa_app_le_player__b40830_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['-last_played'], name='ttsa_app_pl_last_pl_c34dda_idx'),
        ),
        migrations.AddIndex(
            model_name='videolesson',
            index=models.Index(fields=['-created_at'], name='ttsa_app_vi_created_56673b_idx'),
        ),
    ]
