# Generated by Django 6.0.3 on 2026-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0007_videolesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
