# Generated by Django 6.0.3 on 2026-07-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0008_remove_videolesson_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('registration_deadline', models.DateField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_slots', models.IntegerField(default=0)),
                ('available_slots', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('open', 'Open'), ('junior', 'Junior'), ('senior', 'Senior'), ('women', 'Women'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], db_index=True, max_length=20)),
                ('format', models.CharField(choices=[('swiss', 'Swiss System'), ('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('team', 'Team Event')], max_length=20)),
                ('rounds', models.IntegerField(default=1)),
                ('time_control', models.CharField(help_text='e.g., 90+30 for 90 minutes + 30 seconds increment', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['status', 'date'], name='ttsa_app_to_status_de8799_idx'), models.Index(fields=['category', 'status'], name='ttsa_app_to_categor_be9b8d_idx'), models.Index(fields=['date', 'status'], name='ttsa_app_to_date_4eea7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=0, help_text='Tournament points scored', max_digits=10)),
                ('rank', models.IntegerField(blank=True, help_text='Final rank in tournament', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament', 'status'], name='ttsa_app_to_tournam_5094e3_idx'), models.Index(fields=['player', 'registration_date'], name='ttsa_app_to_player__406328_idx')],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
