# Generated by Django 6.0.3 on 2026-07-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0009_tournament_tournamentregistration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournament',
            name='ttsa_app_to_status_de8799_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='ttsa_app_to_categor_be9b8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='ttsa_app_to_date_4eea7b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='tournamentregistration',
            name='ttsa_app_to_tournam_5094e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournamentregistration',
            name='ttsa_app_to_player__406328_idx',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
