# Generated by Django 6.0.3 on 2026-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0010_multiplayergame_lobby_fallback_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['id_number'], name='ttsa_app_pl_id_numb_cbbed4_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['phone_number'], name='ttsa_app_pl_phone_n_303777_idx'),
        ),
    ]
