# Generated by Django 6.0.3 on 2026-07-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsa_app', '0010_remove_tournament_ttsa_app_to_status_de8799_idx_and_more'),
        ('ttsaadmin', '0005_tournament_tournamentplayer_tournamentgame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsa_app.playerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsaadmin.tournament')),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['player', '-registered_at'], name='ttsa_app_to_player__04e09c_idx'), models.Index(fields=['tournament', 'status'], name='ttsa_app_to_tournam_5094e3_idx'), models.Index(fields=['tournament', '-points'], name='ttsa_app_to_tournam_8ffad3_idx'), models.Index(fields=['status', '-registered_at'], name='ttsa_app_to_status_d62193_idx')],
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
